# Generated by Django 5.2.7 on 2025-11-03 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0002_alter_car_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loan',
            table='loans',
        ),
        migrations.AlterModelTable(
            name='manufacturer',
            table='manufacturer',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
