# Generated by Django 5.2.7 on 2025-11-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0003_alter_loan_table_alter_manufacturer_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price_per_day_usd',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(),
        ),
    ]
