# Generated by Django 5.2.7 on 2025-11-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0004_alter_car_price_per_day_usd_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='founded_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
