# Generated by Django 5.2.7 on 2025-11-05 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0005_alter_manufacturer_founded_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='founded_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 5, 9, 24, 13, 938495, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='global_sales',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
